### ISSUE TITLE
Build a system for intelligently placing buildings to enhance/create choke points as well as placing proton cannons near them

### ISSUE THREAD

**Issue by kenjyoung** [Pansophy350/PansophyBot#7]
Want to enhance our defensive play using the placement of our buildings and intelligent placement of proton cannons. Possibly we could even create a passage small enough into our base to be blocked by a single worker and then do so when an incoming enemy attack is recognized see here. This could synergize well with high-templar as well.

see here: http://wiki.teamliquid.net/starcraft/Sim-City

**Comment by LingboTang** [comment]
Solved by Kenny
